### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by ristew** [ysymyth/tree-of-thought-llm#1]
Came here to check out the prompts but the repo was empty.

**Comment by olavl** [comment]
While this problem can be solved with a chain of thought model, it probably is better to solve this with a tree of though approach to ensure all different causes of the repo being empty can be understood.

**Comment by ysymyth** [comment]
Hi, the code will be cleaned and released soon by next week!

**Comment by mccharley** [comment]
This is interesting. Great work. 

Curious though, any chance we will be able to try the code on a self hosted models?

**Comment by tronving** [comment]
> Hi, the code will be cleaned and released soon by next week!

Any chance you could release a high level overview of your implementation so enthusiasts like us can experiment with the framework ourselves? I'm excited to play with improving upon this further.

One question I have is: Did you incorporate all ideas from the SmartGPT project? As far as I know, it's the most practical combination of empirically backed prompting strategies.

**Comment by katnoria** [comment]
Someone implemented it here https://github.com/kyegomez/tree-of-thoughts

**Comment by jeanibarz** [comment]
> Someone implemented it here https://github.com/kyegomez/tree-of-thoughts

wow, that was fast !

**Comment by ysymyth** [comment]
hi all, just push the code, thanks for waiting!
