### ISSUE TITLE
Problems reproducing the text example with GTP-3.5

### ISSUE THREAD

**Issue by code-ksu** [ysymyth/tree-of-thought-llm#13]
Hello Shunyu, I'm currently trying to reproduce your code, but I've encountered an issue. I'm curious to know if it should work properly with GPT-3.5 Turbo. Unfortunately, I'm unable to reproduce it successfully. 

Additionally, I'm wondering why the 'value' of 'method_evaluate' parameter doesn't seem to work for the text task. I would appreciate it if you could provide some insight into these matters. Thank you in advance for your response.

Here is the command I encountered when I tried:
```
python run.py --task text --task_file_path data_100_random_text.txt --prompt_sample cot --backend gpt-3.5-turbo --task_start_index 0 --task_end_index 1 --method_generate sample --meth
od_select sample --method_evaluate vote --naive_run
Namespace(backend='gpt-3.5-turbo', temperature=0.7, task='text', task_file_path='data_100_random_text.txt', task_start_index=0, task_end_index=1, naive_run=True, prompt_sample='cot', method_generate='sample', method_evaluate='vote', method_select='sample', n_generate_sample=1, n_evaluate_sample=1, n_select_sample=1)
```

**Comment by ysymyth** [comment]
Hi, can you show exactly where goes wrong for me to better help?

**Comment by code-ksu** [comment]
I'm unable to specify the exact location of the error because I did not recieve one. After I ran the code without making any modifications. I've already sent you the command I ran inside the conda console on my windows machine. I didn't receive any further responses or feedback after this. Also no error was shown.

**Comment by ysymyth** [comment]
can you check if there's any logs in ``logs/``?

**Comment by ysymyth** [comment]
I'll close for now, but feel free to open new ones
