### ISSUE TITLE
Using Azure OpenAI Service

### ISSUE THREAD

**Issue by dualitycafe** [ysymyth/tree-of-thought-llm#15]
So... only a few developers have ever been given access to the GPT4 API by OpenAI. Not everyone has GPT4 API access. Many of us still waiting for over 3 months now.

Good news is that Azure is offering GPT4 access to businesses that have a corporate entity, website and Azure subscription ID.

Please let me know which part of the code to modify to make this work with Azure OpenAI Service. Maybe make the URL configurable and don't assume an OpenAI key. I'm not sure how Azure OpenAI service works as far as authenticated access is concerned, but it probably involves a secret key, too. 

I can update this issue once I have access to Azure OpenAI Service....

UPDATE:

It's hopeless since they are tightly controlling who gets onboarded and which use cases, etc. In other words, a giant amount of red tape that idea-stage startups won't be able to go through.

However, there is this project https://github.com/acheong08/ChatGPT-to-API/ that converts the OpenAI web UI into an API by reusing the auth tokens. I wonder if your project can be made to work with it, and I think it should be doable. 

Will update this thread as I'm sure there are many of us out there without GPT4 API access. Lots of ridiculous unwarranted red tape, a manufactured situation. 

Thanks

**Comment by ysymyth** [comment]
Thanks for raising this issue! You should only need to change ``models.py`` to enable new API ports. Let me know how to better help.

**Comment by ysymyth** [comment]
I'll close it for now, but happy to pull in any new LLM support when it comes up! Also feel free to open new issues if needed.
