### ISSUE TITLE
How can I build a chat bot to use with this ?

### ISSUE THREAD

**Issue by morrisonricardo** [ysymyth/tree-of-thought-llm#16]
I would like to run data analysis in a similar fashion as Chat GPT with this.
Do you know how I could go about doing that? I do have my GPT4 Key license.

Thank you in advanced 
Richard

**Comment by ysymyth** [comment]
Hi, incorporating interaction with human is an interesting idea! What use case are you concretely considering?

Maybe you can modify ``run.py`` to incorporate human-in-the-loop for thought generation, evaluation, and selection, intervening when needed?

**Comment by ysymyth** [comment]
I'll close it for now, but feel free to open new issues if needed.
