### ISSUE TITLE
Usage instructions without cli

### ISSUE THREAD

**Issue by cvarrichio** [ysymyth/tree-of-thought-llm#20]
I know you're unhappy with kyegomez's code, but that is a package that can be imported into a python program.  To replace that, you need:

1.  The ability to import this into other projects, or at least a way to execute that doesn't use the command line
2. Clear usage instructions for how one might use this to solve an arbitrary prompt ("Combine the following numbers using only basic arithmetic operations (+,*,/,-) to get to some result.", etc)

**Comment by ysymyth** [comment]
Good idea! I'll package and update readme about how to do ToT with new tasks soon. Stay tuned!
