### ISSUE TITLE
Future request: implemented work with GPT4ALL

### ISSUE THREAD

**Issue by TwoTeeToRoomTwo** [ysymyth/tree-of-thought-llm#21]
I have opened the issue there as well. If you can combine these two apps, that would be great!

**Comment by ProxyAyush** [comment]
i want to request this too, i want to see how TOT will perform with other models

**Comment by ysymyth** [comment]
It's beyond my expertise, but that would be great! Happy to merge pull requests if people try this, and I'm also happy to provide any help needed.
