### ISSUE TITLE
Prompts in a standard format for tree appreciators from the future 🌲 

### ISSUE THREAD

**Issue by bmorphism** [ysymyth/tree-of-thought-llm#3]
This item is to inquire as to the possibility of using the prompts separate from the codebase for application in critical infrastructure, and to see if you were open to perhaps publishing just the comprehensive prompts in case my team could help with some of the cleanup 😅

We use an unusual approach for prompt construction and provably safe query string handling (https://www.unison-lang.org/learn/the-big-idea/) and need to either establish or adopt a common way to integrate composable prompts from the Python ecosystem.

**Comment by fblgit** [comment]
Not sure if these two are related, 
https://github.com/fblgit/tree-of-knowledge-llm

**Comment by ysymyth** [comment]
hi, code is released, thanks for waiting!

will close it for now and feel free to open new ones for new questions!
