### ISSUE TITLE
Wow @kyegomez, thanks for sharing an implementation on cutting edge research like this! Amazing work, can’t wait to try it out

### ISSUE THREAD

**Issue by fblgit** [ysymyth/tree-of-thought-llm#4]
Wow @kyegomez, thanks for sharing an implementation on cutting edge research like this! Amazing work, can’t wait to try it out

_Originally posted by @paolorechia in https://github.com/ysymyth/tree-of-thought-llm/issues/2#issuecomment-1557697114_

**This aint a model or a dataset, it seema more like 
autogpt chains. The accuracy is 50/50 >in two calls.. makikg a dozen will be slower and even espensive. Stills a good arriculation of the reasoning.**

**Comment by paolorechia** [comment]
I only tested with a local 7b model, it seemed to struggle to get the voting prompt right. If we can combine this with guidance (https://github.com/microsoft/guidance), I imagine it should work fine.

**Comment by kyegomez** [comment]
Let's implement it! We're doing this right now at: https://github.com/kyegomez/tree-of-thoughts

**Comment by ysymyth** [comment]
hi, code is out, thanks for waiting!

will close it for now and feel free to open new ones for new questions!
