### ISSUE TITLE
I have Tree of Knowledge Data how Train Model

### ISSUE THREAD

**Issue by fblgit** [ysymyth/tree-of-thought-llm#6]
Hi,

I thought the paper spoke about an algorithm .. and not about a lang-chain prompt.
I've created 
https://github.com/fblgit/tree-of-knowledge-llm
Which in theory, if you have the model algorithm.. this will work.

**Comment by ysymyth** [comment]
Thanks for sharing! As it's not an issue for our repo, I'll close it for now.
